name: flutter_login
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.19.0-345.0.dev <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  cupertino_icons: ^1.0.2
  amplify_auth_cognito: ^1.6.0
  amplify_authenticator: ^1.5.1
  amplify_flutter: ^1.6.0
  http: ^0.13.3
  youtube_player_iframe: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true



